### ISSUE TITLE
https://drinco.xyz/xft link broken

### ISSUE THREAD

**Issue by Blueberryy** [drincoxyz/gmod-xft#1]
404 not found

**Comment by drincoxyz** [comment]
yeah the entire website is being done from scratch. right now it's only up so people can download some FGD files from my workshop addons.

hopefully I'll have the website up and running sometime next week. if not, it'll definitely be up whenever XFT is in a good, playable state.

here's the repo for the website: https://github.com/drincoxyz/website-personal
